#ifdef _WIN32
#ifndef BASECLASSES_PCH_HPP
#define BASECLASSES_PCH_HPP
#define WIN32_LEAN_AND_MEAN

#include <Object/Tracer.hpp>
#include <String/String.hpp>
#include <BitSet/BitSet.hpp>
#include <Date/Date.hpp>
#include <Date/Interval.hpp>
#include <Email/EmailEx.hpp>
#include <Email/PmdfEmail.hpp>
#include <Email/mimemessage.hpp>
#include <Encryption/Encryption.hpp>
#include <Encryption/Md5.hpp>
#include <File/LocalFile.hpp>
#include <File/LocalPath.hpp>
#include <File/Progress.hpp>
#include <File/RemoteFile.hpp>
#include <FileSystem/FileSystem.hpp>
#include <FileSystem/LocalSystem.hpp>
#include <File/MMapFile.hpp>
#include <HashTable/HashTable.hpp>
#include <HashTable/VectorTable.hpp>
#include <Internet/Cookie.hpp>
#include <Internet/CookieStorage.hpp>
#include <Internet/EmailAddress.hpp>
#include <Internet/HtmlParser.hpp>
#include <Internet/HtmlTag.hpp>
#include <Internet/HttpRequest.hpp>
#include <Internet/MimeParser.hpp>
#include <Internet/Url.hpp>
#include <Io/HttpIo.hpp>
#include <Io/Io.hpp>
#include <List/Iterator.hpp>
#include <List/List.hpp>
#include <Mutex/Atomic.hpp>
#include <Mutex/Mutex.hpp>
#include <Mutex/RWMutex.hpp>
#include <Mutex/RWNamedTable.hpp>
#include <Object/Exception.hpp>
#include <Object/Handler.hpp>
#include <Object/Object.hpp>
#include <platform/classtypes.hpp>
#include <platform/debug.hpp>
#include <platform/defines.hpp>
#include <platform/include.hpp>
#include <platform/messages.hpp>
#include <platform/platform.hpp>
#include <RegExp/RegExp.hpp>
#include <Server/Connection.hpp>
#include <Server/PingClient.hpp>
#include <Server/Server.hpp>
#include <Server/WebServer.hpp>
#include <Server/NTService.hpp>
#include <Socket/SockTypes.hpp>
#include <Socket/Dns.hpp>
#include <Socket/Socket.hpp>
#include <String/StringPair.hpp>
#include <String/StringTable.hpp>
#include <String/TSStringTable.hpp>
#include <Virtual/VirtualMemory.hpp>
#include <Virtual/FileMapping.hpp>
#include <Thread/PosixThread.hpp>
#include <Thread/Thread.hpp>
#include <Thread/Win32Thread.hpp>
#include <Thread/ThreadPool.hpp>
#include <Thread/ThreadPoolJob.hpp>
#include <Tree/Tree.hpp>
#include <Tree/UrlTree.hpp>
#include <Tree/Md5Tree.hpp>
#include <Vector/IntVector.hpp>
#include <Vector/IntVecIter.hpp>
#include <Vector/Vector.hpp>
#include <Vector/SVector.hpp>
#include <Security/Win32SecInterface.hpp>
#include <Security/State.hpp>
#include <Security/Authentication.hpp>
#include <Security/SspiAuth.hpp>
#include <Security/BasicAuth.hpp>
#include <Security/NtlmAuth.hpp>
#include <SwapVector/SwapBlock.hpp>
#include <SwapVector/SwapVector.hpp>
#endif
#endif
